Iter9
baby-platom/links-shortener pull request #12
Opened 2023-07-03 15:55 UTC by baby-platom

Сдал т к дедлайн, хоть все тесты и пройдены, но есть еще свой план:
- по красоте вынести запись в "short-url-db.json" дополнив server.Shutdown
- больше логгирования добавить где имеет смысл

2023-07-03 20:15 UTC, valentinsoe commented
> Сдал т к дедлайн, хоть все тесты и пройдены, но есть еще свой план:
> 
> * по красоте вынести запись в "short-url-db.json" дополнив server.Shutdown
> * больше логгирования добавить где имеет смысл

Спасибо за предупреждение, явное всегда лучше неявного. Дедлайн мягкий, нет прямо нужды в него уложиться, если есть понимание, что нужно доделать работу.
Я также буду трактовать это как "Просьба вернуть на доработку", даже если меня все устроит:)

2023-07-03 20:52 UTC, valentinsoe requested changes
Спасибо за работу.
В целом по коду все аккуратно и понятно, без лишних усложений(что хорошо)
Но есть замечания - я их здесь дублировать не буду, они все расписаны.

2023-07-03 20:52 UTC, valentinsoe commented on cmd/shortener/main.go
> +	err := app.Run()
Мегазанудство:
Даже если хочется такие вещи сделать, лучше от этого воздержаться.
Причина простая. Они ни на что толком не влияют, а diff становится больше. И это дело не только в моей лени, как ментора в практикуме, но и в будущем в работе.
Лишние изменения делают PR больше и отвлекают от сути.

2023-07-03 20:52 UTC, valentinsoe commented on cmd/shortener/short-url-db.json
> +   "_38ujyQ1t": "https://practicum.yandex.ru"
Можно в репозиторий было бы не добавлять:)

2023-07-03 20:52 UTC, valentinsoe commented on internal/app/api.go
> +	"go.uber.org/zap"
Все-таки лучше настроить goimports в IDE
Пакет zap закрался в пакеты стандартной библиотеки:)

2023-07-03 20:52 UTC, valentinsoe commented on internal/app/api.go
> +		w.WriteHeader(http.StatusInternalServerError)
Кажется это все-таки почти наверняка BadRequest, а не InternalServerError :)

2023-07-03 20:52 UTC, valentinsoe commented on internal/models/api.go
> +type ShortentRequest struct {
Занудство - ShortenRequest. t -лишняя

2023-07-03 20:52 UTC, valentinsoe commented on internal/app/api.go
> +	if reflect.ValueOf(req.URL).IsZero() {
Не надо использовать рефлексию там, где можно написать req.URL == ""

2023-07-03 20:52 UTC, valentinsoe commented on internal/app/api.go
> +		logger.Log.Error("Error encoding response", zap.Error(err))
В данном случае клиент с одной стороны получит код 201, что все хорошо. Но в теле ответа будет что-то не то.

2023-07-03 20:52 UTC, valentinsoe commented on internal/app/server.go
> +		config.Config.Address,
А почему middleware ушли из роутера? Кажется там им самое место.

2023-07-03 20:52 UTC, valentinsoe commented on internal/compress/midleware.go
> +			r.Header.Get("Content-Type"),
shouldBeEncoded должно решать по заголовку Content-Type ответа сервера, а не запроса клиента.

2023-07-03 20:52 UTC, valentinsoe commented on internal/compress/midleware.go
> +func stringInSlice(a string, list []string) bool {
По названию функции не очень понятно что она делает.
Могу предложить название containsString и поменять параметры местами:)

2023-07-03 20:52 UTC, valentinsoe commented on internal/compress/midleware.go
> +		sendsGzip := strings.Contains(contentEncoding, "gzip")
Content-Encoding должен не содержать gzip, а быть ему равен.
Клиент же знает каким конкретно алгоритмом он сжал тело запроса:)

2023-07-03 20:52 UTC, valentinsoe commented on internal/shortid/data.go
> +	return os.WriteFile(fname, res, 0666)
Если записей накопится много, могут быть race condition при записи в файл(исправлять сейчас не надо)
Формат файла также не совсем соответсвует тому, что в задании. Но это не принципиально на данном этапе.

2023-07-08 06:51 UTC, baby-platom commented on internal/app/api.go
> +		w.WriteHeader(http.StatusInternalServerError)
Ориентировался на материал спринта)

2023-07-08 07:05 UTC, baby-platom commented on internal/shortid/data.go
> +	return os.WriteFile(fname, res, 0666)
<img width="548" alt="image" src="https://github.com/baby-platom/links-shortener/assets/82268688/0bc0f373-6d92-4b26-80cf-f1553f8d82ee">
или в каком плане формат файла не тот?

2023-07-09 10:39 UTC, baby-platom commented
От идеи сохранять данные при shutdown сервера все же отказался сейчас)

2023-07-11 20:08 UTC, valentinsoe approved these changes
Спасибо за исправления!
Работу принимаю!

2023-07-13 03:43 UTC, merged