Iter5
baby-platom/links-shortener pull request #7
Opened 2023-06-12 12:14 UTC by baby-platom

2023-06-12 12:16 UTC, baby-platom commented
нечаянно смержил iter3 пиар в мастер и делал откат

2023-06-13 20:16 UTC, valentinsoe requested changes
Спасибо, что вовремя сдал работу! Молодец, что не усложняешь код раньше времени.
Хорошо, что придерживаешься соглашений об именовании.

Замечания по стилю кода и структуре проекта я написал.
Еще бы хотелось все-таки более аккуратно организованных тестов(чтобы каждый тест был отделен).

Поправь, пожалуйста указанные недочеты.

В общем - так держать!

2023-06-13 20:16 UTC, valentinsoe commented on cmd/client/main.go
> +package main
Практиковаться писать вспомогательные вещи для тестирования тоже на Go - хорошо.

2023-06-13 20:16 UTC, valentinsoe commented on cmd/config/main.go
> +package config
В папке cmd принято распологать пакеты main разных приложений.
Такой пакет лучше отнести в internal, да и имя файла тоже не отражает содержимого.

2023-06-13 20:16 UTC, valentinsoe commented on internal/shortid/main.go
> +	"github.com/teris-io/shortid"
В целом, я считаю скорее плюсом, что ты не стал сам изобретать велосипед и использовал готовый пакет. Но не все со мной согласятся.

2023-06-13 20:16 UTC, valentinsoe commented on internal/shortid/main.go
> +	sid, _ := shortid.New(1, shortid.DefaultABC, 2342)
Я бы предложил в качестве seed передавать или какое-то случайное число rand.Int64, или если ты хочешь передавать конкретный seed, то лучше такие вещи выносить в константы.
Потому что 2342 - это магия:) И лучше ей дать конкретное название.

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main.go
> +type customHandler struct{}
Кажется это что-то лишнее:)

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main.go
> +	fmt.Printf("test/n%s/n/ntest", string(body))
Занудство(можно не исправлять)
Кажется, если нужен отладочный вывод, лучше его облагородить, например:
fmt.Printf("Shortened \"%s"\" to \"%s\"[n", string(body), id)

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main.go
> +	shortenedUrlsByID[id] = string(body)
Занудство(можно не исправлять).
Такая конструкция не очень надежна. Что будет если GenerateShortID - вернет нам повтор?:)

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +			name: "positive test #1",
Маловато test-кейсов:)

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +	path string, body io.Reader) (*http.Response, string) {
Лучше так не разбивать определение функции на строки. Если пришлось разбить - принято каждый параметр писать на отдельной строчке. Это значительно более "читаемо"

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +func TestShortenURLHandler(t *testing.T) {
Вот тут у меня много вопросов.
Что будет если второй запустить без первого из IDE?
Что будет если инструментарий запуска тестов такой, что запускает тесты параллельно для ускорения(и не будет соблюден порядок)?

Рекомендую поразмыслить, как можно было бы написать тесты таким образом, чтобы каждый хендлер можно было протестировать отдельно и в любом порядке.
Подсказка - для этого возможно стоит поменять и основной код.

У нас не курс про тестирование, но негативных сценариев тоже нет:)

2023-06-13 20:16 UTC, valentinsoe commented on cmd/shortener/main.go
> +func RestoreURLHandler(w http.ResponseWriter, r *http.Request) {
Не критично для первого спринта. Но хотелось бы реализацию логики приложения видеть отдельнной от старта приложения.
То есть в main по-хорошему должны остаться только чтение конфигурации, связывание компонентов и запуск. А реализация всех компонентов(хранилище, хендлеры, возможно даже роутер) уже в internal.

2023-06-18 05:34 UTC, baby-platom commented on cmd/shortener/main.go
> +	shortenedUrlsByID[id] = string(body)
https://github.com/teris-io/shortid#life-span

2023-06-18 05:35 UTC, baby-platom commented on internal/shortid/main.go
> +	"github.com/teris-io/shortid"
Предпочту согласиться и не мудрить)

2023-06-18 05:36 UTC, baby-platom commented on cmd/shortener/main.go
> +	fmt.Printf("test/n%s/n/ntest", string(body))
артифакт, забыл выпилить

2023-06-19 20:57 UTC, valentinsoe approved these changes
Спасибо за исправления!
Завтра у нас 1:1, там еще можем обсудить некоторые мелкие вещи.

2023-06-19 20:57 UTC, valentinsoe commented on internal/config/parse.go
> +func ParseFlags() {
Занудство: Название функции не самое удачное кажется(мы не только флаги обрабатываем).
Ну и название файла тоже:)

2023-06-20 06:39 UTC, merged